# Part 1

# Load the environment
from dotenv import load_dotenv
load_dotenv()

# Read the model name
import os
MODEL_NAME = os.environ["GEMINI_MODEL"]
API_KEY = os.environ["GOOGLE_GENERATIVE_AI_API_KEY"]

# Create the LangChain model
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model = MODEL_NAME, api_key = API_KEY, temperature = 0 )

# Create the document objects
from langchain_core.documents import Document

documents = [
    Document(
        page_content="LangChain provides abstractions for building LLM applications.",
        metadata={"source": "langchain.txt"}
    ),
    Document(
        page_content="LangGraph is designed for stateful agent workflows.",
        metadata={"source": "langgraph.txt"}
    ),
    Document(
        page_content="Retrievers are components that return relevant documents for a given query.",
        metadata={"source": "retrievers.txt"}
    ),
    Document(
        page_content="Vector stores are used to store and search vector representations of documents.",
        metadata={"source": "vector_stores.txt"}
    ),
    Document(
        page_content="Embeddings represent text as numerical vectors that capture semantic relationships.",
        metadata={"source": "embeddings.txt"}
    ),
    Document(
        page_content="RAG combines information retrieval with language generation to provide context to an LLM.",
        metadata={"source": "rag.txt"}
    ),
    Document(
        page_content="LCEL allows LangChain components to be composed into executable pipelines using the pipe operator.",
        metadata={"source": "lcel.txt"}
    ),
    Document(
        page_content="RunnableParallel allows multiple Runnable components to execute using the same input.",
        metadata={"source": "runnable_parallel.txt"}
    ),
    Document(
        page_content="RunnablePassthrough forwards the original input without modifying it.",
        metadata={"source": "runnable_passthrough.txt"}
    ),
    Document(
        page_content="RunnableLambda converts a Python function into a Runnable component.",
        metadata={"source": "runnable_lambda.txt"}
    ),
    Document(
        page_content="Prompt templates provide a reusable structure for constructing prompts dynamically.",
        metadata={"source": "prompt_templates.txt"}
    ),
    Document(
        page_content="Structured output allows an LLM response to follow a predefined schema.",
        metadata={"source": "structured_output.txt"}
    ),
    Document(
        page_content="Pydantic models can be used to define and validate structured data returned by an LLM.",
        metadata={"source": "pydantic.txt"}
    ),
    Document(
        page_content="Tool calling allows an LLM to request that an external function or system be used.",
        metadata={"source": "tool_calling.txt"}
    ),
    Document(
        page_content="A tool call contains the name of the requested tool and the arguments generated by the LLM.",
        metadata={"source": "tool_calls.txt"}
    ),
    Document(
        page_content="The application executes a tool after receiving a tool call from the LLM.",
        metadata={"source": "tool_execution.txt"}
    ),
    Document(
        page_content="Tool descriptions help an LLM understand when a tool should be selected and how it should be used.",
        metadata={"source": "tool_descriptions.txt"}
    ),
    Document(
        page_content="Similarity search retrieves documents whose vector representations are close to the query vector.",
        metadata={"source": "similarity_search.txt"}
    ),
    Document(
        page_content="Maximum Marginal Relevance can improve retrieval diversity by balancing relevance and similarity between retrieved documents.",
        metadata={"source": "mmr.txt"}
    ),
    Document(
        page_content="Metadata filtering allows retrieval results to be restricted using attributes associated with documents.",
        metadata={"source": "metadata_filtering.txt"}
    ),
]

# Create the embedding model
from langchain_google_genai import GoogleGenerativeAIEmbeddings

embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-001",
    google_api_key=API_KEY,
)

# Create the vector store
from langchain_core.vectorstores import InMemoryVectorStore

vector_store = InMemoryVectorStore(embedding = embeddings)

vector_store.add_documents(documents)

# Create the formatting function
def format_docs(documents: list[Document])->str:
    docs = "\n\n".join(
        f"Page content: {doc.page_content}\n Page_source: {doc.metadata}"
        for doc in documents
        )
    return docs

# Convert the format function to runnable
from langchain_core.runnables import RunnableLambda
format_docs_runnable = RunnableLambda(format_docs)


# Create the retriever
retriever = vector_store.as_retriever(
    search_kwargs = {
        "k": 3,
        "fetch_k":10,
    }
)

query = "What is LangGraph?"


# Create retriever chain
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
retriever_chain = RunnableParallel({
    "context": retriever| format_docs_runnable ,
    "query":RunnablePassthrough()
})

# Create prompt
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
prompt = ChatPromptTemplate.from_messages(
    [
    ("system", "Answer the given query based only on the given context. If context does not provide the answer say I dont know"),
    ("human", "Question: {query}, \nContext: {context}"),
    ]
)

# RAG chain
from langchain_core.output_parsers import StrOutputParser
initial_rag_chain = retriever_chain | prompt | llm | StrOutputParser()|RunnableLambda (lambda x:str(x))

# first_respond = RAG_chain.invoke(query)
respond = ""

# Create the history
from langchain_core.messages import HumanMessage, AIMessage
"""history = [ 
    HumanMessage (content= query), 
    AIMessage (content=respond)
    ]"""

# query_2 = "What is the difference between it and LangChain?"

# Create query rewriter prompt
from langchain_core.prompts import  MessagesPlaceholder
query_rewriter_prompt = ChatPromptTemplate.from_messages(
    [
    ("system", "You are going to receive a history and the current query. Your job is to rewrite the second query so it can be understood without the context of the history with no ambiguity. If the history is empty this mean the query is the initial query, you suppose to return it with not change"),
    MessagesPlaceholder("history"),
    ("human", "Question: {query}"),
    ]
)

# Create history prompt
history_prompt = ChatPromptTemplate.from_messages(
    [
    ("system", "Answer the given query based only on the given context. If context does not provide the answer say I dont know"),
    MessagesPlaceholder("history"),
    ("human", "Question: {query}, \nContext: {context}"),
    ]
)

# Create rewritten query chain
query_rewriting_chain = RunnableParallel({
    "rewritten_query" : query_rewriter_prompt | llm | StrOutputParser() | RunnableLambda (lambda x:str(x)) ,
    "query": RunnablePassthrough()
    })

# Create retriever chain
retriever_chain = RunnableParallel({
    "context":  query_rewriting_chain | RunnableLambda (lambda x:x["rewritten_query"]) | retriever | format_docs_runnable ,
    "history": RunnableLambda (lambda x:x["history"]) | RunnablePassthrough(),
    "query":RunnableLambda (lambda x:x["query"]) | RunnablePassthrough()
})

# Create the conversational RAG
conversational_rag_chain = retriever_chain | history_prompt | llm | StrOutputParser()


print(respond) # >> Based on the provided context, the difference is that LangGraph is designed for stateful agent workflows, whereas LangChain provides abstractions for building LLM applications.

# Part 2
history = []
print("\nStart\n")

while True:
    query = input("You: ")

    if query.lower() in {"exit", "quit"}:
        print("Goodbye!")
        break

    if not history:
        respond = initial_rag_chain.invoke(query)
    else:
        respond = conversational_rag_chain.invoke({
            "query": query,
            "history": history
        })

    print(f"AI: {respond}")

    history.append(HumanMessage(content=query))
    history.append(AIMessage(content=respond))

